import pandas as pd
import numpy as np
import os

def create_features(processed_data_path='../data/processed/'):
    print("Starting RFM Feature Engineering and Churn Labeling...")
    
    # Load cleaned data
    try:
        df = pd.read_csv(os.path.join(processed_data_path, 'olist_cleaned.csv'), low_memory=False)
    except FileNotFoundError:
        print("olist_cleaned.csv not found! Run data_merge.py first.")
        return None
        
    # Ensure datetime format for relevant columns
    date_cols = ['order_purchase_timestamp', 'order_approved_at', 
                 'order_delivered_customer_date', 'order_estimated_delivery_date']
    for col in date_cols:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors='coerce')
            
    dataset_end_date = df['order_purchase_timestamp'].max()
    
    # Calculate order approval delay and delivery delay
    df['order_approval_delay'] = (df['order_approved_at'] - df['order_purchase_timestamp']).dt.total_seconds() / 3600
    df['avg_delivery_delay'] = (df['order_delivered_customer_date'] - df['order_estimated_delivery_date']).dt.days

    # Group by customer_unique_id
    rfm = df.groupby('customer_unique_id').agg(
        # RFM
        recency=('order_purchase_timestamp', lambda x: (dataset_end_date - x.max()).days),
        frequency=('order_id', 'nunique'),
        monetary=('payment_value', 'sum'),
        
        # Extra Features
        avg_review_score=('review_score', 'mean'),
        avg_delivery_delay=('avg_delivery_delay', 'mean'),
        order_approval_delay=('order_approval_delay', 'mean'),
        total_product_categories_bought=('product_category_name_english', 'nunique'),
        avg_freight_value=('freight_value', 'mean'),
        
        # We handle preferred_payment_method separately
        preferred_payment_method=('payment_type', lambda x: x.mode().iloc[0] if not x.mode().empty else 'unknown')
    ).reset_index()

    # Fill NaNs generated by missing values
    rfm.fillna(0, inplace=True)
    
    # Churn Label Creation
    # Churn = 1 if bought once AND > 180 days since last order
    rfm['churn'] = ((rfm['frequency'] == 1) & (rfm['recency'] > 180)).astype(int)
    
    # One-hot encode preferred payment method
    rfm = pd.get_dummies(rfm, columns=['preferred_payment_method'], prefix='payment')
    
    # Save features
    save_file = os.path.join(processed_data_path, 'rfm_features.csv')
    rfm.to_csv(save_file, index=False)
    
    print(f"Feature engineering complete! Final RFM dataset saved to {save_file}. Shape: {rfm.shape}")
    print(rfm['churn'].value_counts(normalize=True) * 100)
    
    return rfm

if __name__ == "__main__":
    create_features(processed_data_path='../data/processed/')
